name: fitfolio
description: A new Flutter project.
version: 1.0.0+1
publish_to: none
flutter:
  uses-material-design: true

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  google_fonts: ^4.0.4
  email_validator: ^2.0.2
  carousel_slider: ^4.2.1
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.1



dev_dependencies:
  flutter_test:
    sdk: flutter